spring:
  application:
  name: whatsapp-integration
  main:
    allow-bean-definition-overriding: true

server:
  port: 5300

# custom props
api:
  whatsapp:
    api-key: ${WHATSAPP_API_KEY:abcd12342}
    sender-phone-id: ${SENDER_PHONE_ID:488062677732676}
