spring:
  application:
  name: whatsapp-integration
  datasource:
    url: jdbc:mysql://docker-mysql:3306/whatsapp_integration?allowPublicKeyRetrieval=true&useSSL=true
    username: ${PRIMARY_DB_USERNAME:root}
    password: ${PRIMARY_DB_PASSWORD:rootUser@123}
    drive-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    # database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    database: mysql
    open-in-view: false

server:
  port: ${SERVER_PORT:5300}

# custom props
api:
  whatsapp:
    api-key: ${WHATSAPP_API_KEY:apiKey1234}
    sender-phone-id: ${SENDER_PHONE_ID:phoneId1234}
    callback-validation-token: ${CALLBACK_VALIDATION_TOKEN:abcd12342}
  chatgpt:
    model: gpt-4-turbo
    api-key: ${OPENAI_API_KEY:apiKey1234}
