name: Deploy Dockerized Spring Boot + WhatsApp Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t whatsappintg:latest .

      - name: Tag Docker image
        run: docker tag whatsappintg:latest ${{secrets.DOCKER_USERNAME}}/whatsappintg:latest

      - name: Push Docker image
        run: docker push ${{secrets.DOCKER_USERNAME}}/whatsappintg:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            docker pull ${{secrets.DOCKER_USERNAME}}/whatsappintg:latest
            docker stop whatsappintg || true
            docker rm whatsappintg || true
            docker run \
              -d \
              --restart unless-stopped \
              --name whatsappintg \
              -p 5300:5300 \
              -e "WHATSAPP_API_KEY=${{secrets.WAPI_ACCESS_TOKEN}}" \
              -e "PHONE_NUMBER_ID=${{secrets.PHONE_NUMBER_ID}}" \
              ${{secrets.DOCKER_USERNAME}}/whatsappintg:latest
